### ISSUE TITLE
User stories - first version

### ISSUE THREAD

**Issue by vulong264** [LTKFoundation/clinic_booking_project#2]
### User Stories
=====PHASE 0=====
#*_Guest_*

1. Search for doctors using any of the following query conditions:
	a. Doctor's Name
	b. Clinic's Name
	c. Clinic's Address
	d. Topic (that relates to Doctor's expertise). E.g: search for "examine child's fever" bring up list of Doctors that are specialized in Pediatric.
	e. Open time. E.g: search for Doctor that provide service at 8pm tomorrow.
	f. By default, system shows all doctors with default sorting conditions.
2. Sorting doctors with the following conditions:
	a. Nearest distance to current location. In this first phase, we focus on Saigon and Hanoi.
		i. Current location is detected automatically if allowed.
		ii. Input current location manually.
	b. Expertise of Doctor. For this first phase, we focus on Pediatric (nhi khoa) and Obstetrics (sản khoa).
	c. Opening time of the clinic (where the desired Doctor works).
	d. Price range of deposit cost for booking.
	e. By default, system sort doctors by nearest distance (if allowed), soonest available opening time, higher Up vote Doctor first. 
3. For each Doctor being display ON THE RESULT PAGE (defaul/after search/after sort), the following information are shown:
	a. Clinic's Name (Note to team: ussually Doctor will use their name as the clinic name. E.g: "Phòng khám bác sĩ Hùng").
	b. Doctor's Name.
	c. Doctor's expertise.
	d. Next opentime (day, time) NEXT TO A "BOOK NOW" button.
	e. Service price (for checkup only).
	f. Clinic's Address. NEXT TO A "SHOW MAP" button.
	g. Current rating result (Average rate) and Total Number of Comment (Click on total Number of Comment show Doctor details page with comment section opended).
4. View a Doctor's Profile (described in Doctor Stories below) 
5. Register to become *_User_* Only User can Vote/Comment on a Doctor and Book for a checkup. 
	a. Guest can chose to register using: Facebook OR Google OR Phone number
	b. After FB/G/Phone authentication, the additional info for User to input are(optional):
		i. Display name. By default, we fill in this form with data receive from authentication step (Name OR Email OR SMS). User can edit this to their preferred value.
		ii. Citis where User lives.
		iii. Payment information (Optional until they want to BOOK)

#*_User_*

1. Rate a doctor 1-5. With a 1-3 rating, require to input a Comment.
2. Write a Comment on a Doctor's Profile.
3. Book for a timeslot in the upcoming Opening day of a selected Doctor:
	a. When viewing the Opening schedule of a Doctor, system allows User to see which timeslot are reserved and which are still available for booking.
	b. User click on the timeslot they prefer. System shows the Booking Info Page.
	c. The Booking Info Page shows:
		i.
		ii.
		iii. BOOK NOW button. 
	d. When click on BOOK NOW. 
		** If there is NO payment method saved: User is required to enter payment method.
			i. After input payment method. User click PAY NOW to start payment process.
			ii. Payment fails. Go back to input payment method form.
			iii. When payment succeed: Display success booking page with booking information including BOOKING NUMBER. Send BOOKING NUMBER to User's email AND/OR SMS.
			iv. On success booking page. Allows User to "save this payment method for future use". If User chose this:
				iv.1. Requires to enter a phone number (if User was not created by phone number). (EXPLAIN: This is to protect User in case they lost their FB/G account. Anyone control their FB/G account now can access to our site, but can only do payment if they can hack User SMS communication too).
				iv.2. Systems send verification code to User Phone number.
				iv.3. User enter verification code into System. If matched. Payment information is saved into database.  
		** If there is payment method saved:
			i. Inform User that they have a payment method already added. A verification code will be sent to the registered number(masking number with ****, only shows the first 3 digits and the last 3 digits) 
			ii. If User enter correct verification code. Load payment information.
			iii. If User lost their phone number or chose to use a new payment method. Bring up Input payment method form.    
4.  Use BOOKING NUMBER at Clinic.
	a. When User arrives at the Clinic, show Doctor/staff the BOOKING NUMBER to be serve at the reserved time.
	b. Doctor/staff input BOOKING NUMBER into System. Receive information about booking. Click on "CLIENT ARRIVED" button. BOOKING STATUS is now ARRIVED. 
	c. When requires to pay the checkup service fee (as listed on our system). User only has to pay the remainder of Checkup Fee - Booking cost (deposit).
	d. After receiving checkup service. User can give feedback about service given:
		i. Uber style -> scale from 1-5. With 5 is most happy. If rating is 1-3. Requires to input a reason. (NOTE TO TEAM: later on when we have bigger data of rate, change frontpage display to show Rate with actual booking).
		ii. Once feedback is submitted. BOOKING STATUS changes to FINISHED.
		iii. If User doesn't feedback. After 12 hours of BOOKING TIME. System sends email/sms to ask about the service received. Message content a link to the rating page. The message also says that if User does not response, system will flag the BOOKING as FINISHED.
	e. If User arrives to the Clinic later than BOOKING timeslot:
		i. If Doctor allows re-arrangement/wait list: go to 4.b -> 4.c -> 4.d
		ii. If Doctor does not allow re-arrangement/wait list. BOOKING is treated as not show up.
	f. If User doesn't show up. After 12 hours of BOOKING TIME. System sends email/sms to ask about what happened? With a link for User to write their reason. Inform User that BOOKING STATUS is finished.
	g. If User arrives at the Clinic on time but was made wait over the booked time OR the Doctor can not provide the service AT ALL.
		i. On BOOKING INFO page. Allow User to REPORT BAD SERVICE. Recommend User to contact our hotline immediately to receive REFUNDS.
		ii. When contacted for REPORT BAD SERVICE. We contact client immediately and try to resolve with Doctor right away. (NOTE TO TEAM: A customer support DASHBOARD needed). 
	h. In case Doctor has sudden situation and can not provide service in booked time. User receive a notification via Emails/SMS. We process to REFUNDS the Booking Deposit.

#*_CLINIC_*
1. We pupulate a list of predefined Clinic available. Each clinic has the following info:
	i. Clinic's Name.
	ii. Address.
	iii. Phone Number.
	iv. Location on Map.
	v. License number 
(NOTE TO TEAM: for phase 1. We leave it this way. In later phase we will implement a better management function for Clinic Owner Account)

#*_DOCTOR_*
(NOTE TO TEAM: in production. At the begining we/our staff will be the one contacting Doctor and collect info and do 
all of the registration process for opening a doctor account/ clinic account)

1. Creates account using FB/G/Email. The registration form includes the following madantory fields:
		i. Email(get from authentication or manual input) *
		ii. Phone number *
		iii. Name * 
	After input, verify Doctor's Phone number.
	Additional information (can edit later)	
		iv. Short introduction
		v. Expertise
		vi. Experiences
		vii. Certification
		viii. Photo
2. Uploads certification documents for approval.
3. Select the Clinic where Doctor works at from existing list. If Clinic not exist. Create a Clinic account.
	 Create Clinic process:
		i. Clinic's Name.
		ii. Address.
		iii. Phone Number (can be and should be different from Doctor's verification phone number).
		iv. Location on Map.
		v. License number.
4. Create Opening Time Schedule at this Clinic (remember later on one Doctor can work at different Clinics on different days).
	i. Setups working days of the week. Set if these available days will repeat weekly
	i. Setups working hours of each day/everyday.
5. Setups booking fee (deposit amount ) at the selected Clinic. 
6. Define Service Cost for checkup.
7. Views rating result.
8. Views comment on my profile me.
9. Replies to comment from User.
10. Write "article" to publish on my profile page/public page.
11. Using Client Booking Dashboard:
	i. View the dahboard showing list of upcoming User and their booked timeslot.
	ii. When there are client come without booking. Easily enter their name into the next available timeslot.
	iii. When a User with BOOKING show up. Enter their booking code to verify. If the code is correct. BOOKING TIME SLOT update status as "ARRIVED" (change color to green maybe)
	iv. If a User not show up after BOOKED time has passed. Status of that timeslot update to not show up (color changes to RED)
12. View Reports:
	i. Summary Report showing all client served in day/week/month. Client are seperated by online booking and no booking
	ii. More additional report here...

#*_ADMIN_*
_CUSTOMER_SUPPORT_
* Review and approve registration of Doctor
* Remove spam review of User
* 
_SYSTEM_ADMIN_

//END OF PHASE 0
=====PHASE 1=====

* User can add multiple patient (wife,kid, etc..).
* Doctor can enter prescription given to a patient.
* User and Doctor can communicate directly via chat.
* User and Doctor can view treatment history.
* A clinic can add multiple doctors. Can add different calendar for each doctor.
* One doctor can chose to be working at different clinic in different time/day. 

=====PHASE 2=====
* User can request for and Doctor can provide home checkup service
* Open to all medical services

**Comment by taduyvinh** [comment]
I'm thinking about BOOK NOW button, after user book for specified time, should the doctor receive a notification and CONFIRM one more time to the user before continuing to the payment page? But the dashboard should still be updated after payment has been made successfully to prevent spamming. This is only to make sure users will surely have the service, cuz sometimes the doctors are suddenly busy but they dont update their opening time i think ?

**Comment by vulong264** [comment]
@taduyvinh In the beginning I thought about the same thing! However, let's look at how it will run on User's perspective:
1. User do BOOK NOW before PAYMENT: so I clicked on BOOK NOW. And now I have to wait for the DOCTOR to confirm. When will he confirm? How long will I have to wait? Ah crap, it's too long. I'll just go do other thing and get rid of this booking thing for once and all.
2. User follows our current workflow and perform PAYMENT. Now he has to wait for doctor to confirm on the Booking WHILE HE PAID THE MONEY ALREADY. This is unacceptable.
Hence the current approach.
1. Doctor put on an Opening Hour Schedule. He must commit to that schedule. We also provide him the Dashboard to use at their clinic so that he can input regular client in between our prebooked User
2. In case of in-advoidable cancellation of the service session. System allows him to send cancel notification to User. This cancelation will be displayed on his profile so he can't let it happens too often.
3. If doctors can't keep up with their booked plan. The lost is on them. User can complain and we will refund. There will be low vote and bad comment on Doctor's profile

**Comment by tucq88** [comment]
Out of date. Close.
